apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default 
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.30.1
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/prometheus/values.yaml
    - repoURL: https://github.com/ThiagoLange/web-page-deploy.git
      targetRevision: HEAD
      ref: values
      # parameters:
      #   - name: "server.service.type"
      #     value: "LoadBalancer"
  destination:
    namespace: monitoramento
    server: https://kubernetes.default.svc
 
